# syntax=docker/dockerfile:1.3-labs

############## STAGE 1 - Prepare the image for GCS installation ################
FROM debian:12

# Prereqs
RUN <<EOF
    set -e
    apt update
    # Resolves: "debconf: (Can't locate Term/ReadLine.pm in @INC" from python install
    apt install -y libterm-readline-gnu-perl
    apt install -y \
        coreutils \
        gzip \
        python3 \
        python3-venv \
        sudo \
        tar
EOF

##################### STAGE 2 - Install GCS using Ansible ######################
# This is the base64 compressed tar of the ansible repo directory
COPY <<EOF /ansible.64
H4sIAAAAAAAAA+0c/VfbOLI/56+YDfcebd/ZJgkh3Szhjm0p5R1beITuu31cL1VsJdFiW17Lhma3
/d9vRrITyAdJgKa3XQ+PxJGlkWYkjeZDEguV6PrcefIFYQuhUa/rb4TJb/1c2d6p7lS3Ko3KzpOt
SqXS2HkC9S/ZqBxSlbAY4EksZXJXvkXv/6TAsv7Pvm2313/0OqiDd7a35/V/Zau6PdH/tWqj8gS2
Hr0lM+Av3v8XHu+x1E/U+9JGaQP237aPfjw+6Lw8efv66LAJ5wOhgIdXIpZhwMMErlgsGA4UuBa+
DwmnjwGHbPiAK4OAhR5iuh7wmEMioSdCD/Mgnp7AAQavsgrpnZvGMWH1RMzdRMZDG1uBhV/LOGBJ
E59G9bXw0U85/KDrwEKU71i6LBEyBNmDgVQJ+EIlT9WzkgivMAsibNnO6LlUiqXPVSdiyaClHwnH
fooNYVdSeEqTcjpMBjKsAY9jGRMZIYgEesz3FXSZewlYnZOq2OmK0Il0ZkrCoohsM+aBTPgmqKFK
eGBDm3MiY5AkkWo6jiddZY/mmgzyeef4LOEqcWLeQ7aFLu+wKOKhJ1yukICEx1HM8bPjCeXKK46c
GiSBX7r5yrSlxZAeouuVDDcTiGIR9mFTXQrE521CwtSlKiGWyGfDTpbcId4pZDFSqXjpa4/JAtYH
+fij4dCV8tIeBv5j17FA/uPL6qT8r9cahfxfB1habqomoHwrAWip2MQHAAv6vuymynJlGKJ0thSP
UfAU0uGbgnz+647/QlbA6vp/tVatFvr/OuB2/8+c8Q8eFav3/069vlX0/zpgmf7PTYT7DoSV+7+6
Vas3iv5fB6zU/wET4T0UxMX6385E/+MA2Cr0v3XABiD9OAA+pWH2QHYo2oyf0Kq0TFKp76pOzCPZ
zDIXOuA3A8vM/ysWP0g1XH39b9SrtUL+rwOW7v97yn6CRfK/hp19W/5XKo1C/q8FtFzviLAnPhrD
30j4kaQHyBeG5ugJE7NFopk/YNJ4vRgVLnXiAfc70WW/E/TjJpT/+AM2h2lAA6wn+lbAQtbn8SaI
HjzNRiJ5OJNYdFPy63YC9quMOzgIFXl5Wy3YbGw+A+4rDpte2INJRJ8/l4vFaRVYZv5rn/EDFoBl
5X9ju1LboXyVRmOrXsj/dcDy/S9o9vs+CgxvwJJVloK75X9lq1KZlP+17UoR/1sLbKwMpQ3QcPS2
fb5/fLx/fnTyFl6fnMEZ996wBF4dnB39jKk/H7Tt0j3QmzhkFk/sMTdRFN3TgS5ca5r6dR5v7EjV
6bFA+MNmXv0naOuYl8d8fjPn/GWlCQ0s9QL/v8f/T1Cr08cOfTTmYWjCvh+wYxGmHzHfSx4mJ218
eM09GTN8OImZ6/P8/ahpZ9K9HE40kWJ1R0Ek40SHHw9OD47hkg+Bf4x84YrEH0KXuyzFJY/e55zB
ZRQC6aX46EmuKNZHkT9LaFSIE3HogOYQrtmQsju0YFLYtmRByAJcpo/MlB7Xe3b6E5BCoATFSwkF
LuxYu6TcQ64oQhAFHUw3MQJ6GMc2fbun6Y9i+SuKD1vGfSdKuw6PuO8gauvw9ND618EvFtVloS6w
xJL/+TNWREHYPCgxqwx814Ky4X25NJ+6MWVTVCF7TAWm6HIk0YcVc58zxS0TwF2aKjuULHYHNrJT
14tNTbBiVKIUxbZXpXkDDnnIYyR3CMzHDlc5Kpw5cHDcABGghqQAC4PPk0184qDSmNtT/JpW0Bax
i0pgo3x1P1KmtbxyQ9N0oKeAL5IhiFFn0oaEK04Bd5n2BxSbxxQGSvYS8DgFzXnoDrOQ/LjjaeDm
EwlRm7likI62ENzGIZBdiNqwIo31LgQWepgrwDlH7ZcKBuyKUxvwN2Xwptk5raYuYieWsLKNFE9v
l3z2KAz+bsRgFCAd5MSgI5Fm4blErwxpDCF2iWgC4uPB8QvkSiyukFFXyJSnNIhCmWRy7dmI5FeG
CZrxU6gzYYWt4iyYYkG+J6KbCh8NCluh4eAbmtzA0zwZibusFms4Vcn9BtuL8qJ5ZggtT4jqw+OT
H9+1v4awPnzZfqCsltehL5mnbKPyacGWSOlfisTpJzuOseAcqsBBNLfE96EuMlvQUstutMrjPREK
4qNaWubOatpsxRSF7S379SJ3VL5HCZsrrNjRYzIyPPQ7k9grCeIcvx4UY4P3xqJzcwoYPsFL02ho
60ZntvGYSYJPs2bRbChrym/Y1kgvWFY+M0zFVlaxZSq26lY7a+0dRKlRluXoPQgXkJs5CL4IvTy8
k9xzU/VcemnuJ+M8j0Rw7iX5GhS/C9XdXUwkp+Gjd/K41N1UuzLKpJFHujw4PHEdlAO2LmV7s+c5
EjauQGc1fJJoE4SI5VPJWCQX89hyiqXN2H+fZSW6WrNpqQNmh3bu6SLoooKXxn4rF1HUabfl0wpC
K5esKI2ojz1BXessqzc6f6PGkMRyssb1mPBpR2DAUSPyWmhZIO+TYfbWDBivVcl+569b37/IUvpR
3x1w93KUBRNwrWjRbk2kVXdRdCmowRa+mrUSAG3TzLYNEUGZp8+ozvO9e9qfZ1TYkVOP+8aJd8f4
ffAQRdXm4/Ri6YuQ0zqCVOtaaZfoA0cooWya6loKTT9VHyBHkTVEj0429g2QesvjhPXQyEVaTl4v
S//4tUGH+ptecrk3vTzP5MuiVXkmufXtWUvl13ZlFHAPWN3/5/GuYCuFghbEf7a3GtuT/r9ao174
/9YB9/b/Tbn/3nXTMEmdV3p4rNPxl9e4nK+vsgWfoFKhD3L5VelntTq3dObeaQLOC2wIZu6mPq5U
Q06PmEO4+NCTLvPx+1cWBOTfu0QJnAh3vvfQtBlzGq6RF/CB1hSLklyz6q7BmMJabhpTHWNMdTCL
ja9mLQ/LL9XZAqkXPNR679Qo8aXP3OklG9nhKJnGLlc2HQqZu3Lfrmyu/y4bB+S5I3S6upj30e5v
wuZ/N/6jniPZsJmlmzbBZp72aObW6ublDK/AQ1lmqrgnq+ZwagOW5tXDzJJpfsw0SpZmxriOlRgy
ZbwQ+RdK9FF1s7rDlj5hpAYs5jen2Qzl20ad/D08pmVCLVlMiqYA07+Cpj63w/DfJocpdVauEs/m
9r77Wypi3mwS45pNnbPZnOIeDrp5anv5h8fU0d9FHgpL4zM8PQeXoUk2X8SnOndH5zIvZ68eSyn8
I6yFwv8XhNX1f5UqvtpGsEX6/059cv93rVKrFvr/OuDe+v+0AXByevC2/a598IV3AIx8SeCT1q2P
/VrBtEOVJ2n0bL7V0DZxwOVshvoi+6DchO25eTI8ZUJkz83WBApiaQYecxZNbQxYPtr0+zCKcB1d
IeCUlfi2402GyCLkdM+AxHhUid5Qt+hbDjjNovZbDjfdg94/ZbCJ6HT+mtEmUtzmxpn+7yNMqxmZ
q8U8pleGFawguHk/isHx5vz8tN05PTv59y86FLY514o0wbFZtmEeEDPhsC9may2v/9//AMjC8x87
k/p/pbZdK/T/dcDUhEF9KmLuJW0WvB3Xxfehx2JP/M5zJTqbzpBtBGuC2Rs+Sh5vc516ZRzgTTDR
pHGJlHztJKlKFBR1/dTjHT3+TGVaZEA5t0VJG5tu18WUuk/KGY3d4nDIJOTzf3RJ0heoY9H836o3
Ju9/qewU57/WAhcjI/p9qVJt2Fv4VxmpCNlCgIpBS+crps+3Bvn8PzvYf/XTgR14X6COBfO/tl2t
TN7/sl0v4v9rgd1uDM5eaTcC5ot+2Cq7nPxs5T1cbncHtclUUg9yN9NpdmXYrjOoIQYn2iuVdj2e
oLWgtC+rVaZPg0qlQcDi4d65tttkj1RysqfUrpO/omzS39Pr/K4v9jKlYJfBIOa9VnmDdWWaWGgY
WtlxjPLePiXBOV3bZ5J2HXYHBlLdUb9FhcHyRSASvfNflffaOl3v7j8ep49xOTmymVgH8trypCUs
VFssOqBg9WR863CBKu+NVJw38ho8CUdg3HZ0L6KM4Vbuf+RVzG7AuGZfYMcoXt47Ng9UYF5eMmAZ
8eylebgj78sBC/vcl33MnD/ezL7rUD/tOllnY79vbMBUV5T05ZFZV9H3lUBDHMjrR65HlqCeF43c
mx6PfDnUd0zi6LiYabi9f5rbxNfX1/Nt32fIWvIAZQPVhiOsihBgD+ujIjjjtYsokgKrI/bz0DM/
mBeIkAxjhsqQGjmduUfnaMiFGjD6caO1VByJ81LXHCMZe6CiNI6k4soeTZnLUF6jrdzn+syKwpGP
uLCtrvF38I8siNAOM5drBuZCy0vuDyHkmDGRdGiHeSxKzK+eSGAo0/imBWqXSs+f4zS9qsMAqRXk
PL+m0y094Qo6H2RlXEcUF7cOwCARLvdSJHfMZ31f5SIng3VVvzXarX6KPe08e/7cNheIjtyi2hmt
j45kkX8zDnTNysw/c54nI1u/NdFOfV9ochub9gFoXvmsDz2Okzgmp5B2yeuggWaErcfnUvOuVLHh
EJvg+jI0faLrwKo1n2/xK5Secdl8+PBB+9P0j79Bf1Q+5yKmDNKuvu/TMHAOH82osjF7jrdUtUem
WX4xaXayCQdxnyf5RaOlGt01mqQRWm9KXcvY84mj7fYbw7eJ/JTIcEC7rkzDxPCZhotKkUWYimXt
0rYNZ2kIHzIdwcrviATLGt+vumvwdgzevb/jS2Rw3No1N6F26Mce3Lxe8oPpj0xklfaRNGzvpTlr
FQ1j0R8YkfAuFNotlQz1gjEQLutLnExYQGdSQC4Y5JxnMGaCrXRq9iiYS2XpYsORoPktpamJPU30
f8hS/zke39i0r70gF1BAAQUUUEABBRRQQAEFFFBAAQUUUEABBRRQQAEFFFBAAQXcE/4HRNgY+wB4
AAA=
EOF

RUN <<EOF
    set -e
    /usr/bin/python3 -m venv /venv
    /venv/bin/pip install --upgrade pip
    # Install wheel to avoid the warning that setup.py is being used when
    # installing Ansible
    /venv/bin/pip install wheel
    /venv/bin/pip install ansible
    cat /ansible.64 | base64 -d | (cd /; tar zxf -)
EOF

ARG GLOBUS_ANSIBLE_OPTIONS

# Modifying this arg value on the build command line will cause RUN to reinstall
# Globus instead of using the previous, cached iteration (if it exists). Useful
# for speeding up re-runs to get newer Globus versions.
ARG CACHEBUST=1

RUN <<EOF
    (cd /ansible; /venv/bin/ansible-playbook playbook.yml ${GLOBUS_ANSIBLE_OPTIONS})
EOF

######################### STAGE 3 - Prepare GCS Image ##########################
LABEL maintainer="support@globus.org"

# This is the base64 compressed tar of entrypoint.sh
COPY <<EOF /entrypoint.64
H4sIAAAAAAAAA+1ZW3MbtxX2a/ZXwJTGlKbeJalIdketnHEtxdHEuowk180kHRrcBUmUS+wWwIpm
mv73fgfYXS4vsp2p5bwIDyIJHByc63cOIKGsnueZVDYy40f3M7oYzw8OHnV7ewcHe/vud2/ff+Lb
wbcH+496+897B8+edfefY773Legfse49ybM0CmO5ZuzRRBoj0o/RCW2+hkBfd2w97gyk6gy4GQfB
1pcdwRZ79/Lq/PT89SF7wwsVj6UasdevrtlM2nFWWGbmxoppwqRh4kMutJwKZXkasbdGMG7ZPCs0
y2aKaWkmEfi9yqY5t3KQCsfDMTuI9qO93p++uPQBKXAzFiznmk+Fhf/ZTDAlRMJsxlKnEWurLBHM
CFvkbcY1USOQoJJit5IzoW6lzhTpBW63XEsO4Q10AX+2fXxy+ebip7OT85v+jyc/sSP2V6ESl479
RORpNqeN/YmYvyDq84vjk/71yc3by/7Lq9fXIM9yKzPFU5w8MmyY6WV5dsSHiIWhzEOeJFoYs0ts
Xr+5+Nvb6/718Y/9k/O/n15dnJMATW6JuBVpltPhSxoEcsh+ZuGvrLUieYv9M7BjoQKGIeJxxlpn
SCjyd2N/rT9rL29vR+zkg7QW9FHL88BP1guG8j6i8vrm5JL1DhFNaihHBZwG2ZkzHJnwdZoNCsMG
c6YLpUiHplHvJ87OMz3laTp/ytojd3wYZ0qJ2IbAnVuhWdOtM5mmLC/wJ6HkqIRvm1J08ItL1Th5
lHGVVPGKQxDCMWKB6zlLsxjupiMkpiL2QzaD6/VTBtfFgsIdIQ12s0xPyBBcZwV40YkARJYNFyms
WKYTCIrUGPNbbFSsULmWtzIVIyQEJLJcKjAnfsITOWKVpM4DYAheuWHIemDxbZ0mHjIgeDwW8cT5
iCRAjICe5IQcdgwQGcrU8ZzyCXh5x2JakkU4JvI80xay5Cm34DKN2BlRItQ4G7o9GXYAeCBfDAVK
2Ur7gElpxIaAesrCIXMg6k0R2zRIFQuNn7S6EKvLYHQJ9CNwW2Q5Q5bDipCeez1mYwEFlvKZZNKC
QwJpg2WAOGp1FhMhJqJ/mUy1ApeMqzjzgm0v7w7i8TRL2LNud20l+FQ8UrqyX1zWhuGyDKvMSrJV
ICtxZfs7FirBuutY0jhsyGGbxOPF14SLvaqGuWSaZkpahGGVORT+qRRFIyPuASdImq2tSg7KijOu
+Ehot+RM1V4utOV6uypmLhlc8ry8PGW5zggIfMgDGLKZoZJLGcSTqVSUXmWqlVVpHVmoJiIz8ckL
FHUtf6WzXbdU8kUQ85jOoQVX0RvcCjdLR9xorsxQ1DYtc7/CF/FBxIWFpUex6U+9WpHJ4omwziMx
8oKWO8DszioNg6Q4GOwGYszTYcROLRmioEpNcBJn02mhZOyVGgg7EwLK5Ug10RlbmyfuEJKzYVbq
SNx5xEtlgA0tratvqB2QYSYGjBqd0ZiABRFK+Ut0XljHrlRBWgDKMPIdhxaQSTwlFJpmt0t0OyRG
LhMHEbvOU8C1AUukRnJmgHQiGMlbJ+gZQS1kqjwQEXfl0M1LgM3zaSrVpNaZzspSr64SM1chyCgG
EoCbd2nTLqSTsYTOQ1mayMsaBcF0ArnWXAKwobLlDXRY2mmNqMTQlemOc+dGJ1O0lKnhhCjDiF0L
AHAqByUAJ+Xn8v4S4XccmsQJ66AX6njk65gxYrgDIf/iVnE2hTcLi8rH4aj+Fi7tJNgfUVxlWpXY
52GS6illyD779Pgl+CYMc42GjMMtuezzPP/0hoQLgNRnsK82QNbkCLJ+ONxs83WREIVrpJgMdskT
7zjivarUVcCipkm4x8gRukxEVOGiclikZWENsA6qn9ljV1Q3MEdtSDJnSJMKkbNudIAJJYIGXR90
R+8Rths5vA9cuzVDM8HVSND1Ap4Yy9x3EXWmVa2AD3YX5tTySEtJ+lkx5fg0KmsH7e9G25ZtNTQu
DGYoavype81SuMWOxUBy1Xk7KJQtfDOtLHoQF7Mup2azGTxv+WH15SOHitSIkvGVSKBq5xXK9MV1
53uRZJpv5O/FOixtcjfvshCvlquXKAK4bxPy31GwagoqWb5gVVXKzFVcdbgrVagCL+oTjAN31y4a
QX1vNgKnKTW8I9QHIKaxCV0+fSxSeSpMQb03fAyotgTeVdUhFDTUnGXUmPlyBIY4QoGAJ0+poLXd
UVULi+XFae6S2k4oEjStmDY6xt+JHxvbL17ZiT1ZCv163iXB9uNgzQ8vve8ceG90Q5OgHfyfsVkW
WsOHrjGnDPLbqQ+mnatsMc/oSca6VShBuHFUR1p5dvUZEd58biA7GqeOhxdh404+kR2bmk4stDUd
dx0aZ8ZGsbbQjzbUOvoTPGv2Z1yJCpRJd4vBppQeBcaut9K+4NfdfrXXaQrMoE7G187QmDQc0Q1G
l9Ihb/wxC2PAZGaF28Jm3osbLeWW/F9nJUrJJXjdLrfcCalu7wJMK/r366mtZfL9zeXmpPZrQEyK
2/anot9mBRg6JQheNwY/wU1Ywc0I/Ic2p9tGsLBLua9aLJOmvKRcV19iHwMlVUSYUi29Wl5KqvnK
Zh72Np3ijL2pkN1FfHdJ86Sr5ewuPu+D+7j8uHaUUjgutEbsAyZVVl2lXYG/OD1+tfqiF335288Q
EeXAXpp+WRL6PEWju7Mb/MeZb0KYH+IG28MFF7fh246iN5K9F096wX8bDNwrQsWj3r1F+0J2zqcV
mGzv4ffl6XHggWPlWCwvAKVxdV3DDH+FBXO6pNLrQ6HosTPG13Teqsk0rrfoEntNHCjnuiS+GRfu
gaxPbz5H3YY6qeCqyGtF/HnXJbl7Ioqi8p68zMSfZTXPoejNydVZ8/fJP05vgnoT0fcbhQYCbDbK
Sh/GnjzZvL/XMN4mAhaKf7Pe3fa8ERo3VG5Xbrpshw5dlWJ3YWYfJKTsGlVQEw2lNqigKKalnDR8
Sh/Wv8ukrcZnmWKAa9ck+Ibod3a2F8fs7tKq14w6Z9IKrm0qhupJAdTyuxsSdhsSKbFipiaHMTdV
DLaqKPOh/gXz1KfOOwFh/JW4ugdUhcCW93zXiuHenafCiuiLy9FIhavyFde9IpXZwuqU+MjzVklL
2eeSotrrUmVpxiWLm2m32Q9vL+vvp+dIooUr6kfQxt0HiOpfycgtVd3YXspUlwzdRaFYQjDWanZs
LbZd1232228bM35leyNGWutR+7t5LHr4FW5LvekmviuQsKz+RiyoPOScXbWBDrNcKa3B1GXGH/2/
tofxMB7Gw3gYD+NhPIyH8TD+6PE/qUbbigAoAAA=
EOF

RUN <<EOF
    cat /entrypoint.64 | base64 -d | tar zxf - > /entrypoint.sh
EOF

# These are the default ports in use by GCSv5.4. Currently, they can not be changed.
#   443 : HTTPD service for GCS Manager API and HTTPS access to collections
#  50000-51000 : Default port range for incoming data transfer tasks
EXPOSE 443/tcp 50000-51000/tcp

# Default command unless overriden with 'docker run --entrypoint'
ENTRYPOINT ["/entrypoint.sh"]
# Default options to ENTRYPOINT unless overriden with 'docker run arg1...'
CMD []
